### ISSUE TITLE
Add wolflu05 to team section

### ISSUE THREAD

**Issue by matmair** [inventree/inventree-website#128]
As @wolflu05 is now a member of Triage, he should be added to the team section.

@wolflu05 What should be your sentence on the team page? You can select freely, I would appreciate it if it is not much longer than the below examples. You can also select what you want to be called, the current team uses first names.
```
Francois is an EE. He is part of the core team and the maintainer of Ki-nTree.
```

```
Matthias is an Austrian developer. He is part of the core team and focuses on enterprise enhancement.
```

**Comment by wolflu05** [comment]
Haha, Texting is a hard job for developers :joy: , maybe something like. Please suggest changes :joy: 
```
Lukas is a German student who likes developing, and building electronics. He focusses on plugin development.
```

**Comment by eeintech** [comment]
`focuses`?

**Comment by wolflu05** [comment]
> `focuses`?

You're right, I don't want to be british (Its actually in the Oxford dictionary like this 😆 ).

**Comment by eeintech** [comment]
Haha my english is more american than british, I don't really know which is true I just found two s to be weird

**Comment by matmair** [comment]
@wolflu05 you are live on the website ;-)
