### ISSUE TITLE
Issues building

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/inventree-website#145]
Getting a new environment setup, and having trouble building the website.

At the step `bundle exec jekyll build`:

![image](https://github.com/inventree/inventree-website/assets/10080325/e9f7aa44-54fb-4c51-b38b-e2e774d0942a)

website runs locally but without any css:

![image](https://github.com/inventree/inventree-website/assets/10080325/6e48a3b3-32e7-4538-9ac9-147ba9f98635)

@matmair any ideas on this one?

**Comment by SchrodingersGat** [comment]
Might be related to https://github.com/tailwindlabs/tailwindcss/issues/8819 but can't work out how...

**Comment by matmair** [comment]
That's a new one for me; Maybe try updating the gems 'bundle update' and if that is not working try reinstalling all deps; the commands are in the readme

**Comment by SchrodingersGat** [comment]
This was from a clean install, following the instructions in README.md.. Will try playing around a bit

**Comment by SchrodingersGat** [comment]
ubuntu 22.04 under wsl btw

**Comment by matmair** [comment]
I have to get out a windows device to reproduce, will report back when I have

**Comment by SchrodingersGat** [comment]
I have (after much hassle) updated to the following versions:

| Package | Version |
| --- | --- |
| gem | 3.4.13 |
| ruby | 3.2.2 |
| bundler | 2.4.13 |
| npm | 8.5.1 |

A different error message now:

![image](https://github.com/inventree/inventree-website/assets/10080325/77b28cd4-360d-4bef-aff8-327c1d099dc0)

**Comment by matmair** [comment]
@SchrodingersGat what node version do you have? You will need 13, better 14

**Comment by matmair** [comment]
@SchrodingersGat I do not think so, the setup is not described in much detail

**Comment by SchrodingersGat** [comment]
I've improved the docs a bit here
