### ISSUE TITLE
Add page for inventree-wireviz

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/inventree-website#147]
Ref: https://github.com/inventree/inventree-wireviz

Once new plugin is released and validated, add a page for it .

**Comment by matmair** [comment]
I never even thought of that - great idea

**Comment by SchrodingersGat** [comment]
It's a WIP but opening up some *great* functionality for my tech team :)

**Comment by matmair** [comment]
Closed by https://github.com/inventree/inventree-website/pull/148
