### ISSUE TITLE
DigitalOcean link is broken

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/inventree-website#39]
![image](https://user-images.githubusercontent.com/10080325/200736155-735ac914-6480-42cf-b203-1d7e5b87297c.png)

simply takes you here:

![image](https://user-images.githubusercontent.com/10080325/200736204-47a2428e-0e32-4ccd-bf01-e52352f7340e.png)

**Comment by matmair** [comment]
@SchrodingersGat the 1-click-app is currently down as it was targeting my custom packages and I would like to wait for the release before re-enabling it

**Comment by matmair** [comment]
works again
