### ISSUE TITLE
Add logos to stats

### ISSUE THREAD

**Issue by matmair** [inventree/inventree-website#54]
It was suggested to me to add icons or logos to the main stats section to make it more interesting.
Thoughts @inventree/maintainer @inventree/triage ?

**Comment by SchrodingersGat** [comment]
I'd tend to agree - I think some logos there would be nice

**Comment by matmair** [comment]
Ok I will look into that

**Comment by SchrodingersGat** [comment]
Can we also add a translation language stat? i.e. "26 languages" - pulled from Crowdin
