### ISSUE TITLE
Add avatars to team section

### ISSUE THREAD

**Issue by matmair** [inventree/inventree-website#55]
It was suggested to add avatars or pictures to the team section along with #54 . I like the clean look of the main site but I can understand the wish for a bit of eye-candy.
Thoughts @inventree/maintainer @inventree/triage ?

**Comment by SchrodingersGat** [comment]
I'd be happy to put a picture there. I think it adds some "legitimacy" to the page. Would you be for a photo of yourself there @matmair ?

**Comment by matmair** [comment]
@SchrodingersGat i was more thinking of the avatars from GitHub but mine is already a picture of me so why not.

**Comment by SchrodingersGat** [comment]
I also think the "team" section should be moved off the home page and into the "about" page - for a cleaner look

**Comment by matmair** [comment]
@SchrodingersGat the idea behind that is to give casual visitors a short idea of who works on the thing, making it a bit more approachable. The main site is a bit short else. Any idea what we could put there instead?
