### ISSUE TITLE
[blog] news reader

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/inventree-website#60]
Blog entry about the new "news reader" functionality

- What it is
- how to enable it

Ref: https://github.com/inventree/InvenTree/pull/3445

**Comment by matmair** [comment]
Not sure how/if this function will be maintained, also probably not interesting.

**Comment by SchrodingersGat** [comment]
Are you suggesting that we do not continue support for "news" in the new interface? I'd be on board with this

**Comment by matmair** [comment]
I am suggesting that if it is not visible or even implemented there is no need for a blood about it.
